plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

jar {
    manifest {
        attributes 'Main-Class': 'org.example.Main'
    }
}

repositories {

    mavenCentral()

    maven {
        url "https://raw.githubusercontent.com/eurotech/kura_addons/mvn-repo/"
    }

}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    // https://mvnrepository.com/artifact/io.ultreia/bluecove
    //implementation group: 'io.ultreia', name: 'bluecove', version: '2.1.1'

     https://mvnrepository.com/artifact/tinyb/tinyb
     implementation group: 'tinyb', name: 'tinyb', version: '1.0.100'

}

test {
    useJUnitPlatform()
}